# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crs_Title', models.TextField(max_length=30)),
                ('crs_Type', models.TextField(max_length=30)),
                ('crs_Description', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.TextField(max_length=30)),
                ('fname', models.TextField(max_length=30)),
                ('email', models.TextField(max_length=50)),
                ('DOB', models.DateTimeField(verbose_name='Date of birth')),
                ('hireDate', models.DateTimeField(verbose_name='Hire date')),
                ('street', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=30)),
                ('state', models.TextField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('empPassword', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GradeScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrLname', models.TextField(max_length=30)),
                ('instrFname', models.TextField(max_length=30)),
                ('instrPhone', models.IntegerField()),
                ('specialty', models.TextField(max_length=30)),
                ('instrPassword', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appr_Date', models.DateTimeField(verbose_name='Approve Date')),
                ('section', models.TextField(max_length=2)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeTraining.Course')),
                ('EmployeeTraining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeTraining.EmployeeTraining')),
                ('GradeScore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeTraining.GradeScore')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeTraining.Instructor'),
        ),
    ]
